# Generated by Django 3.1.2 on 2021-01-23 22:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resorts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('weather', models.JSONField(blank=True, null=True)),
                ('resort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resort_forecast', to='resorts.resort')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('forecasted_at', models.DateTimeField()),
                ('temp', models.DecimalField(decimal_places=3, max_digits=7)),
                ('feels_like', models.DecimalField(decimal_places=3, max_digits=7)),
                ('temp_min', models.DecimalField(decimal_places=3, max_digits=7)),
                ('temp_max', models.DecimalField(decimal_places=3, max_digits=7)),
                ('pressure', models.IntegerField()),
                ('sea_level', models.IntegerField()),
                ('grnd_level', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('temp_kf', models.IntegerField()),
                ('weather', models.CharField(max_length=50)),
                ('weather_id', models.IntegerField()),
                ('weather_description', models.CharField(max_length=200)),
                ('weather_icon_name', models.CharField(max_length=10)),
                ('clouds', models.IntegerField()),
                ('wind_speed', models.DecimalField(decimal_places=3, max_digits=7)),
                ('wind_deg', models.IntegerField()),
                ('visibility', models.IntegerField()),
                ('pop', models.DecimalField(decimal_places=3, max_digits=7)),
                ('rain', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('snow', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('sys', models.CharField(max_length=1)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_details', to='forecasts.forecast')),
            ],
        ),
    ]
