# Generated by Django 3.1.2 on 2021-01-16 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastdetail',
            name='forecast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_details', to='forecasts.forecast'),
        ),
    ]
