# Generated by Django 3.1.2 on 2021-02-07 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0002_auto_20210126_0612'),
        ('forecasts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecastdetail',
            name='detail_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='resort',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resort_forecast', to='resorts.resort'),
        ),
    ]
