# Generated by Django 3.1.2 on 2021-02-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0002_auto_20210207_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecastdetail',
            old_name='detail_index',
            new_name='json_index',
        ),
    ]
