# Generated by Django 3.1.2 on 2021-01-17 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0002_auto_20210117_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastdetail',
            name='forecasted_date',
        ),
    ]
