# Generated by Django 3.1.2 on 2021-02-07 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0002_auto_20210126_0612'),
        ('forecasts', '0003_auto_20210207_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastdetail',
            name='json_index',
        ),
        migrations.AlterField(
            model_name='forecast',
            name='resort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resort_forecast', to='resorts.resort'),
        ),
    ]
