# Generated by Django 3.1.2 on 2020-12-25 12:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('observatories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observed_at', models.DateTimeField()),
                ('highest', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('highest_quality_level', models.IntegerField(blank=True, choices=[(0, '統計しない'), (1, '資料なし、未報告'), (2, '利用不適値'), (3, '疑問値'), (4, '資料不足値'), (5, '準正常値'), (8, '正常値')], null=True)),
                ('highest_observed_at', models.DateTimeField()),
                ('lowest', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('lowest_quality_level', models.IntegerField(blank=True, choices=[(0, '統計しない'), (1, '資料なし、未報告'), (2, '利用不適値'), (3, '疑問値'), (4, '資料不足値'), (5, '準正常値'), (8, '正常値')], null=True)),
                ('lowest_observed_at', models.DateTimeField()),
                ('observatory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='observatory_temperature', to='observatories.observatory')),
            ],
        ),
    ]
