# Generated by Django 3.1.2 on 2021-01-01 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observatories', '0002_temperature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rainfall',
            old_name='rainfall_78h',
            new_name='rainfall_72h',
        ),
        migrations.RenameField(
            model_name='rainfall',
            old_name='rainfall_78h_quality_level',
            new_name='rainfall_72h_quality_level',
        ),
        migrations.RenameField(
            model_name='snowfall',
            old_name='snowfall_78h',
            new_name='snowfall_72h',
        ),
        migrations.RenameField(
            model_name='snowfall',
            old_name='snowfall_78h_quality_level',
            new_name='snowfall_72h_quality_level',
        ),
    ]
