# Generated by Django 3.1.2 on 2021-01-25 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resorts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resort',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resort',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='resort',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='resort',
            name='name_kana',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resort',
            name='postal_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
